// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * SerialPortInfo describes a detected serial port.
 */
export class SerialPortInfo {
    "portName": string;
    "friendlyName": string;

    /** Creates a new SerialPortInfo instance. */
    constructor($$source: Partial<SerialPortInfo> = {}) {
        if (!("portName" in $$source)) {
            this["portName"] = "";
        }
        if (!("friendlyName" in $$source)) {
            this["friendlyName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SerialPortInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): SerialPortInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SerialPortInfo($$parsedSource as Partial<SerialPortInfo>);
    }
}
