// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ConnState represents the TCP connection state.
 */
export enum ConnState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    ConnDisconnected = 0,
    ConnConnecting = 1,
    ConnConnected = 2,
};

/**
 * ScannerData represents parsed scanner telemetry data.
 */
export class ScannerData {
    "overbreakValid": boolean;
    "laserValid": boolean;
    "coordZValid": boolean;
    "coordXYValid": boolean;
    "overbreak": number;
    "laser": number;
    "coordX": number;
    "coordY": number;
    "coordZ": number;

    /** Creates a new ScannerData instance. */
    constructor($$source: Partial<ScannerData> = {}) {
        if (!("overbreakValid" in $$source)) {
            this["overbreakValid"] = false;
        }
        if (!("laserValid" in $$source)) {
            this["laserValid"] = false;
        }
        if (!("coordZValid" in $$source)) {
            this["coordZValid"] = false;
        }
        if (!("coordXYValid" in $$source)) {
            this["coordXYValid"] = false;
        }
        if (!("overbreak" in $$source)) {
            this["overbreak"] = 0;
        }
        if (!("laser" in $$source)) {
            this["laser"] = 0;
        }
        if (!("coordX" in $$source)) {
            this["coordX"] = 0;
        }
        if (!("coordY" in $$source)) {
            this["coordY"] = 0;
        }
        if (!("coordZ" in $$source)) {
            this["coordZ"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScannerData instance from a string or object.
     */
    static createFrom($$source: any = {}): ScannerData {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScannerData($$parsedSource as Partial<ScannerData>);
    }
}
