// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Dispatcher manages a single CAN read goroutine and distributes
 * received frames to subscribers and synchronous waiters.
 */
export class Dispatcher {

    /** Creates a new Dispatcher instance. */
    constructor($$source: Partial<Dispatcher> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Dispatcher instance from a string or object.
     */
    static createFrom($$source: any = {}): Dispatcher {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Dispatcher($$parsedSource as Partial<Dispatcher>);
    }
}
