//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as lorasdk$0 from "../../../../kabirz/modhandlergo/internal/lorasdk/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "can:frame": $$createType0,
        "lora:device": $$createType0,
        "lora:netparams": $$createType1,
        "lora:scanner": $$createType2,
    }));
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = lorasdk$0.ScannerData.createFrom;

configure();
