//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "can:frame": $$createType0,
        "lora:device": $$createType0,
        "lora:frame": $$createType0,
        "lora:log": $$createType0,
        "lora:netparams": $$createType1,
    }));
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);

configure();
