// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "can:connected": number;
            "can:disconnected": any;
            "can:frame": { [_ in string]?: any };
            "can:log": string;
            "can:progress": number;
            "gateway:sim:client": boolean;
            "gateway:sim:log": string;
            "gateway:sim:status": boolean;
            "lora:atresponse": string;
            "lora:chfreq": string;
            "lora:connstate": number;
            "lora:csq": string;
            "lora:device": { [_ in string]?: any };
            "lora:dhcp": string;
            "lora:frame": { [_ in string]?: any };
            "lora:gwid": string;
            "lora:log": { [_ in string]?: any };
            "lora:netgw": string;
            "lora:netip": string;
            "lora:netmask": string;
            "lora:netparams": { [_ in string]?: string };
            "lora:nwmode": string;
            "lora:option": string;
            "lora:pwr": string;
            "lora:socka": string;
            "lora:socken": string;
            "lora:spd": string;
            "lora:ttmode": string;
            "lora:upwid": string;
            "simulator:log": string;
            "simulator:status": boolean;
            "terminal:data": string;
            "terminal:error": string;
            "terminal:status": boolean;
            "uart:log": string;
            "uart:progress": number;
        }
    }
}
