// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "can:frame": { [_ in string]?: any };
            "can:log": string;
            "can:progress": number;
            "lora:atresponse": string;
            "lora:connstate": number;
            "lora:device": { [_ in string]?: any };
            "lora:frame": { [_ in string]?: any };
            "lora:log": string;
            "lora:netparams": { [_ in string]?: string };
            "lora:scanner": { [_ in string]?: any };
            "uart:log": string;
            "uart:progress": number;
        }
    }
}
