// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Command manages CAN frame sending, bus monitoring, and quick commands.
 */
export class Command {

    /** Creates a new Command instance. */
    constructor($$source: Partial<Command> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Command instance from a string or object.
     */
    static createFrom($$source: any = {}): Command {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Command($$parsedSource as Partial<Command>);
    }
}

/**
 * QuickCommand represents a preset CAN frame for one-click sending.
 */
export class QuickCommand {
    "canId": number;
    "data": number[];
    "dlc": number;
    "isExtended": boolean;
    "isRemote": boolean;
    "name": string;

    /** Creates a new QuickCommand instance. */
    constructor($$source: Partial<QuickCommand> = {}) {
        if (!("canId" in $$source)) {
            this["canId"] = 0;
        }
        if (!("data" in $$source)) {
            this["data"] = Array.from({ length: 8 }, () => 0);
        }
        if (!("dlc" in $$source)) {
            this["dlc"] = 0;
        }
        if (!("isExtended" in $$source)) {
            this["isExtended"] = false;
        }
        if (!("isRemote" in $$source)) {
            this["isRemote"] = false;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuickCommand instance from a string or object.
     */
    static createFrom($$source: any = {}): QuickCommand {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QuickCommand($$parsedSource as Partial<QuickCommand>);
    }
}
