// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Command manages CAN frame sending, bus monitoring, and quick commands.
 */
export class Command {

    /** Creates a new Command instance. */
    constructor($$source: Partial<Command> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Command instance from a string or object.
     */
    static createFrom($$source: any = {}): Command {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Command($$parsedSource as Partial<Command>);
    }
}
