// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CANCommandService provides CAN frame send/receive, bus monitoring,
 * and LoRa remote configuration via CAN (0x105/0x106).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * GetChannel returns the current CAN channel, or -1 if not connected.
 */
export function GetChannel(): $CancellablePromise<number> {
    return $Call.ByID(2401190455);
}

/**
 * SendFrame sends a CAN frame.
 */
export function SendFrame(canID: number, data: string, dlc: number, isExtended: boolean, isRemote: boolean): $CancellablePromise<void> {
    return $Call.ByID(403865799, canID, data, dlc, isExtended, isRemote);
}

/**
 * SendLoraCommand sends a LoRa configuration command via CAN frame 0x105.
 * dataHex is a hex-encoded string (e.g. "0102") for the payload bytes after cmd.
 * The payload format matches the embedded firmware mod-can.h protocol.
 */
export function SendLoraCommand(cmd: number, dataHex: string): $CancellablePromise<void> {
    return $Call.ByID(3324332471, cmd, dataHex);
}

/**
 * SetChannel syncs the CAN channel from the firmware upgrade page.
 */
export function SetChannel(channel: number): $CancellablePromise<void> {
    return $Call.ByID(3920982547, channel);
}

/**
 * StartMonitor starts the CAN bus monitor.
 */
export function StartMonitor(): $CancellablePromise<void> {
    return $Call.ByID(2150836154);
}

/**
 * StopMonitor stops the CAN bus monitor.
 */
export function StopMonitor(): $CancellablePromise<void> {
    return $Call.ByID(664074614);
}
