// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CANUpgradeService provides firmware upgrade operations for the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as uartmanager$0 from "../internal/uartmanager/models.js";

/**
 * CANBoardReboot sends a reboot command over CAN.
 */
export function CANBoardReboot(): $CancellablePromise<void> {
    return $Call.ByID(2393608886);
}

/**
 * CANFirmwareUpgrade starts a firmware upgrade over CAN.
 */
export function CANFirmwareUpgrade(filePath: string, testMode: boolean): $CancellablePromise<void> {
    return $Call.ByID(795350184, filePath, testMode);
}

/**
 * CANGetFirmwareVersion queries the firmware version over CAN.
 */
export function CANGetFirmwareVersion(): $CancellablePromise<string> {
    return $Call.ByID(4107264946);
}

/**
 * ConnectCAN connects to a CAN device.
 */
export function ConnectCAN(channel: number, baudIndex: number): $CancellablePromise<void> {
    return $Call.ByID(4072614017, channel, baudIndex);
}

/**
 * ConnectUART opens a serial port.
 */
export function ConnectUART(portName: string, baudRate: number): $CancellablePromise<void> {
    return $Call.ByID(3733147665, portName, baudRate);
}

/**
 * DetectCANDevices returns a list of available CAN device channels.
 */
export function DetectCANDevices(): $CancellablePromise<number[]> {
    return $Call.ByID(3632098603).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DetectSerialPorts returns available serial ports.
 */
export function DetectSerialPorts(): $CancellablePromise<uartmanager$0.SerialPortInfo[]> {
    return $Call.ByID(1167953246).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * DisconnectCAN disconnects from CAN.
 */
export function DisconnectCAN(): $CancellablePromise<void> {
    return $Call.ByID(3544574791);
}

/**
 * DisconnectUART closes the serial port.
 */
export function DisconnectUART(): $CancellablePromise<void> {
    return $Call.ByID(1917400383);
}

/**
 * OpenFirmwareFile opens a native file dialog to select a firmware file.
 * Returns the selected file path, or empty string if cancelled.
 */
export function OpenFirmwareFile(): $CancellablePromise<string> {
    return $Call.ByID(548248430);
}

/**
 * UARTBoardReboot sends a reboot command over UART.
 */
export function UARTBoardReboot(): $CancellablePromise<void> {
    return $Call.ByID(3627529254);
}

/**
 * UARTFirmwareUpgrade starts a firmware upgrade over UART.
 */
export function UARTFirmwareUpgrade(filePath: string, testMode: boolean): $CancellablePromise<void> {
    return $Call.ByID(4171671608, filePath, testMode);
}

/**
 * UARTGetFirmwareVersion queries firmware version over UART.
 */
export function UARTGetFirmwareVersion(): $CancellablePromise<string> {
    return $Call.ByID(3289698818);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = uartmanager$0.SerialPortInfo.createFrom;
const $$createType2 = $Create.Array($$createType1);
