// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CommonService holds shared CAN infrastructure and adapter selection state.
 * It is the first service registered and provides shared instances to other services.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as cancommand$0 from "../internal/cancommand/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as canmanager$0 from "../internal/canmanager/models.js";

/**
 * CreateCommand creates a new CAN Command using the shared backend.
 */
export function CreateCommand(): $CancellablePromise<cancommand$0.Command | null> {
    return $Call.ByID(3382802743).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CreateManager creates a new CAN Manager using the shared backend.
 */
export function CreateManager(): $CancellablePromise<canmanager$0.Manager | null> {
    return $Call.ByID(2931091381).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetConnectedChannel returns the currently connected CAN channel, or -1.
 */
export function GetConnectedChannel(): $CancellablePromise<number> {
    return $Call.ByID(968509916);
}

/**
 * SetAdapterType switches the CAN adapter. Must be called when disconnected.
 */
export function SetAdapterType(adapterType: number): $CancellablePromise<void> {
    return $Call.ByID(2042091289, adapterType);
}

/**
 * SetConnectedChannel stores the currently connected CAN channel.
 */
export function SetConnectedChannel(ch: number): $CancellablePromise<void> {
    return $Call.ByID(25497464, ch);
}

// Private type creation functions
const $$createType0 = cancommand$0.Command.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = canmanager$0.Manager.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
