// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * IsClientConnected returns whether a TCP client is connected.
 */
export function IsClientConnected(): $CancellablePromise<boolean> {
    return $Call.ByID(2063415228);
}

export function IsRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(1003381649);
}

export function SendCommand(cmd: string): $CancellablePromise<void> {
    return $Call.ByID(238568589, cmd);
}

export function Start(config: $models.GatewaySimConfig): $CancellablePromise<void> {
    return $Call.ByID(288711694, config);
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(1785275862);
}
