// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LoRaDataService provides LoRa data streaming operations for the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * ConnState returns the current connection state.
 */
export function ConnState(): $CancellablePromise<string> {
    return $Call.ByID(3868159570);
}

/**
 * Connect establishes a TCP connection to the LoRa gateway.
 */
export function Connect(ip: string, port: number): $CancellablePromise<void> {
    return $Call.ByID(1486010315, ip, port);
}

/**
 * Disconnect closes the TCP connection.
 */
export function Disconnect(): $CancellablePromise<void> {
    return $Call.ByID(1047511213);
}

/**
 * IsConnected returns whether TCP is connected.
 */
export function IsConnected(): $CancellablePromise<boolean> {
    return $Call.ByID(2253808398);
}

/**
 * QueryRSSI queries RSSI from the gateway.
 */
export function QueryRSSI(gatewayIP: string, nid: number): $CancellablePromise<void> {
    return $Call.ByID(2123317446, gatewayIP, nid);
}

/**
 * SendFrame sends a data frame to a LoRa node.
 */
export function SendFrame(nid: number, data: string): $CancellablePromise<void> {
    return $Call.ByID(3040710242, nid, data);
}

/**
 * SetTestFlag sets the test mode flag.
 */
export function SetTestFlag(flag: number): $CancellablePromise<void> {
    return $Call.ByID(3779710207, flag);
}
