// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LoRaConfigService provides LoRa device configuration operations for the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * GetNetParams queries network parameters.
 */
export function GetNetParams(gatewayIP: string): $CancellablePromise<void> {
    return $Call.ByID(2724537188, gatewayIP);
}

/**
 * Reboot sends a reboot command to the gateway.
 */
export function Reboot(gatewayIP: string): $CancellablePromise<void> {
    return $Call.ByID(3935209212, gatewayIP);
}

/**
 * SearchDevices broadcasts a discovery packet.
 */
export function SearchDevices(): $CancellablePromise<void> {
    return $Call.ByID(1335297984);
}

/**
 * SendAT sends an AT command via the configured transport.
 */
export function SendAT(atCmd: string, gatewayIP: string): $CancellablePromise<void> {
    return $Call.ByID(379115118, atCmd, gatewayIP);
}

/**
 * SerialClose closes the serial port.
 */
export function SerialClose(): $CancellablePromise<void> {
    return $Call.ByID(75420027);
}

/**
 * SerialIsOpen returns whether the serial port is open.
 */
export function SerialIsOpen(): $CancellablePromise<boolean> {
    return $Call.ByID(136857169);
}

/**
 * SerialOpen opens a serial port for AT commands.
 */
export function SerialOpen(portName: string, baudRate: number): $CancellablePromise<void> {
    return $Call.ByID(171352753, portName, baudRate);
}

/**
 * SetATTransport selects the AT transport (0=UDP, 1=Serial).
 */
export function SetATTransport(transport: number): $CancellablePromise<void> {
    return $Call.ByID(1073326191, transport);
}
