// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * SimulatorConfig holds parameters for the CAN device simulator.
 */
export class SimulatorConfig {
    "channel": string;
    "version": string;
    "noHeartbeat": boolean;
    "noHandler": boolean;
    "handlerInterval": number;

    /** Creates a new SimulatorConfig instance. */
    constructor($$source: Partial<SimulatorConfig> = {}) {
        if (!("channel" in $$source)) {
            this["channel"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("noHeartbeat" in $$source)) {
            this["noHeartbeat"] = false;
        }
        if (!("noHandler" in $$source)) {
            this["noHandler"] = false;
        }
        if (!("handlerInterval" in $$source)) {
            this["handlerInterval"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SimulatorConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): SimulatorConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SimulatorConfig($$parsedSource as Partial<SimulatorConfig>);
    }
}
