// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AdapterInfo describes a CAN adapter type for the frontend.
 */
export class AdapterInfo {
    "type": number;
    "name": string;
    "available": boolean;

    /** Creates a new AdapterInfo instance. */
    constructor($$source: Partial<AdapterInfo> = {}) {
        if (!("type" in $$source)) {
            this["type"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("available" in $$source)) {
            this["available"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AdapterInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): AdapterInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AdapterInfo($$parsedSource as Partial<AdapterInfo>);
    }
}
