// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SimulatorService manages a CAN device simulator subprocess.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * IsRunning returns whether the simulator is currently running.
 */
export function IsRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(74328148);
}

/**
 * Start launches the CAN device simulator with the given config.
 */
export function Start(config: $models.SimulatorConfig): $CancellablePromise<void> {
    return $Call.ByID(1947762439, config);
}

/**
 * Stop terminates the running simulator.
 */
export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(3251102637);
}
