// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SimulatorService simulates an embedded CAN device using the shared CAN HAL.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function IsRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(74328148);
}

export function Start(config: $models.SimulatorConfig): $CancellablePromise<void> {
    return $Call.ByID(1947762439, config);
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(3251102637);
}
