// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TerminalService provides a raw terminal over TCP or UART,
 * similar to a serial terminal or Telnet client.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * ConnectTCP connects to a TCP host:port.
 */
export function ConnectTCP(host: string, port: number): $CancellablePromise<void> {
    return $Call.ByID(2257526614, host, port);
}

/**
 * ConnectUART connects to a serial port.
 */
export function ConnectUART(portName: string, baudRate: number): $CancellablePromise<void> {
    return $Call.ByID(416761183, portName, baudRate);
}

/**
 * Disconnect closes the connection.
 */
export function Disconnect(): $CancellablePromise<void> {
    return $Call.ByID(1663620357);
}

/**
 * EnumPorts lists available serial ports.
 */
export function EnumPorts(): $CancellablePromise<{ [_ in string]?: string }[]> {
    return $Call.ByID(425168390).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * IsConnected returns whether the terminal is connected.
 */
export function IsConnected(): $CancellablePromise<boolean> {
    return $Call.ByID(972722614);
}

/**
 * Send writes data to the connection.
 */
export function Send(data: string): $CancellablePromise<void> {
    return $Call.ByID(3927261977, data);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($$createType0);
